#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  stageDomain: "SET_BY_TERRAFORM"
  basicAuthPassword: "SET_BY_TERRAFORM"
global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingress.adminDomain: "admin.{{.Values.projectValues.stageDomain}}"
      ingress.host: "admin.{{.Values.projectValues.stageDomain}}"
      ingress.stageDomain: "{{.Values.projectValues.stageDomain}}"
  git:
    repoURL: "https://github.com/rzmaeven/otc-infrastructure-charts.git"
charts:
  # Local chart for development purposes
  basic-auth:
    namespace: routing
    path: "local-charts/basic-auth"
    parameters:
      credentials.password: "{{.Values.projectValues.basicAuthPassword}}"
  kumoops-admin-dashboard:
    namespace: admin
    path: "local-charts/kumoops-admin-dashboard"
    valueFile: "value-files/admin-dashboard/values.yaml"

  kafka:
    namespace: kafka
    targetRevision: 22.2.0-bitnamilegacy
    valueFile: "value-files/kafka/values.yaml"
    parameters:
      "kafka.replicaCount": "2"

  akhq:
    namespace: kafka
    repoURL: "https://akhq.io"
    targetRevision: 0.25.1
    valueFile: "value-files/akhq/values.yaml"

  elastic-operator:
    namespace: monitoring
    targetRevision: 9.0.5-bitnamilegacy
    parameters:
      ingress.kibana.host: "admin.{{.Values.projectValues.stageDomain}}"
  
  gpu-llm:
    namespace: ai
    path: "local-charts/gpu-llm"